version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - D:/University/Projects/Github/url_shortner_fr/url_shortner:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
